# Generated by Django 5.2.3 on 2025-07-16 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='accepted_privacy_policy',
            field=models.BooleanField(default=False),
        ),
    ]
