# Generated by Django 5.2.3 on 2025-07-16 03:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 17, 3, 37, 33, 737720, tzinfo=datetime.timezone.utc)),
        ),
    ]
