# Generated by Django 5.2.3 on 2025-11-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0002_customuser_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='NicknameDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='Уникальный никнейм для анализа', max_length=50, unique=True, verbose_name='Никнейм')),
                ('language_type', models.CharField(choices=[('ru', 'Русский'), ('en', 'Английский'), ('mixed', 'Смешанный')], default='mixed', help_text='Язык, преобладающий в никнейме', max_length=10, verbose_name='Тип языка')),
                ('is_toxic', models.BooleanField(default=False, help_text='1 - токсичный никнейм, 0 - нетоксичный', verbose_name='Токсичный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Никнейм (датасет RNN)',
                'verbose_name_plural': 'Никнеймы (датасет RNN)',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['nickname'], name='idx_nickname'), models.Index(fields=['is_toxic'], name='idx_is_toxic'), models.Index(fields=['language_type'], name='idx_language_type'), models.Index(fields=['created_at'], name='idx_created_at')],
            },
        ),
    ]
