# Generated by Django 5.2.3 on 2025-11-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0003_nicknamedataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nicknamedataset',
            name='id',
            field=models.BigAutoField(help_text='Уникальный идентификатор записи', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nicknamedataset',
            name='language_type',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'Английский'), ('cn', 'Китайский'), ('mixed', 'Смешанный')], default='mixed', help_text='Язык, преобладающий в никнейме', max_length=10, verbose_name='Тип языка'),
        ),
        migrations.AddIndex(
            model_name='nicknamedataset',
            index=models.Index(fields=['id'], name='idx_id'),
        ),
    ]
