# Generated by Django 5.2.3 on 2025-10-01 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_group', models.BooleanField(default=False, verbose_name='Групповой чат')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя чата/Группы')),
                ('last_message_text', models.CharField(blank=True, max_length=255, verbose_name='Текст последнего сообщения')),
                ('last_message_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата последнего сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='chat_avatars/', verbose_name='Аватар чата/группы')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_chats', to=settings.AUTH_USER_MODEL, verbose_name='Владелец/Админ')),
                ('participants', models.ManyToManyField(related_name='chats', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
                'indexes': [models.Index(fields=['last_message_date'], name='messenger_a_last_me_d6221c_idx')],
            },
        ),
    ]
