# Generated by Django 5.2.3 on 2025-10-05 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_api', '0002_chat_administrators_friendship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
