# Generated by Django 5.2.3 on 2025-07-16 03:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo_app', '0002_alter_post_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 17, 3, 52, 40, 310350, tzinfo=datetime.timezone.utc)),
        ),
    ]
