# Generated by Django 5.2.3 on 2025-07-17 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo_app', '0003_alter_post_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 18, 12, 30, 28, 611428, tzinfo=datetime.timezone.utc)),
        ),
    ]
