# Generated by Django 5.2.3 on 2025-08-25 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 26, 6, 9, 50, 452048, tzinfo=datetime.timezone.utc)),
        ),
    ]
