# Generated by Django 5.2.3 on 2025-09-27 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo_api', '0004_comment_disecho_count_comment_echo_count_echo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_floating',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='echo_api.post'),
        ),
    ]
