# Generated by Django 5.2.3 on 2025-09-28 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo_api', '0005_comment_is_floating_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='echo_api.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
