# Generated by Django 5.2.3 on 2025-11-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo_api', '0007_post_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_toxic',
            field=models.BooleanField(default=False, verbose_name='Токсичный'),
        ),
    ]
